[package]
name = "socket_proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
clap = { version = "2.33.3", features = ["yaml"] }
env_logger = "0.8.3"
trust-dns-resolver = { version = "0.20.3", features = ["dns-over-rustls"] }
async-trait = { version = "0.1.50" }
log = "0.4"
backtrace = "0.3"
nix = "0.19"
[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"